language: python
python:
- 3.6.3
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
before_script:
- python -m flake8
script:
- python -m pytest --cov=./k8s_jobs tests/
after_success:
- codecov
branches:
  only:
  - master
  - "/v(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(-(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*)?/"
before_deploy:
- python setup.py sdist
- git clone --depth 1 git@github.com:freenome/freenome-build.git || true
- source freenome-build/scripts/install_latest_stable_freenome_build.sh $ANACONDA_TOKEN
deploy:
- provider: packagecloud
  repository: python
  username: freenome
  on:
    tags: true
  dist: python
  package_glob: dist/*.{whl,zip,egg,egg-info,tar,bz2,Z,gz}
  skip_cleanup: true
  token:
    secure: e2zgT8jvqe0fKUC684qeZA7Td1ocwPmRcACJwU7PbOQmA3V9rHNRhIRdYfBZ0+6xKaj/LH/et5GvO/ulW+01KGFwc/2u19Xa+95pkPQuwOye42ZgF20TUbk9yrKC2aTleCCW7ZP/xShvZX2dtBPktR8cbhp8Ui2Bl+UXRoSx4mFZMiEmAv1fybTY+gSjMyj8G1h4cNZmI2pEhTnePUO8+TAgJIyBwjHRuFwrlkJX+EX1oUutYjdwqGiQBT+LzbLXpYrwDedbsfqtsySxzi0pHPD6yX6R2XYjpOlOSzURiqL9G3RYqdRRIqkC206CoNB4Gdz1HRrRWCJAo1kyZZrpxiG0RPCZnXX7OSQjy1XCkt/0Lsw+xTlco4QESUxKdgM43Wkd5vjX7/ovO5HxCGJO+NzyB63nWvhlv9O247MO5MOgYifjv0Q31vHmzAg2GXeyNHSy2xVT1EG64EQgojFd3cSojSq/qoD0/c0VmPYZCRiWKO3832e6qfNGs5/kvcOI3e+CHWnR80KpfMaUQjeqGgQ8M9VnpeWR+MmRNPo9MPQLecIvki4KQTmKteOkm21jhGY5lUOsFhItAbNjBafWPe2LJ6lEamNXugg+nCzIXDBYSESVSvvTKnF9Kcixj51pWieGfPIy4N53hBt9pMz/HqyHmbIamjBoqeiOPWCxxj8=
- provider: script
  script: freenome-build deploy -u
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: KpqtwdOPilLpGnaenfxPLw3DBcofF5/k5zbf/AK0VfjKMlpOJ8HiFFbAEBpIVxbRGXnRwNEe8byc80IncBjZ46b/ywre3PWWMHLMRFMIJaCNNDi3lfIznuMAK9tv9brNRIRqLmvoANEASf7QtZPncLZ09nmr4n3EFQ+bOF4URq74U/OG90/1U+hqUG8il3sPkcFeTSDAbnFZLQx/F53ErQ8TDBpnutQ7B7gqDey3+vJQkDZjWql/pwkuKj5IkCqkxrPcR3/n5/TK1Us/GG+Ycruf/SrlABqvrjr8Nq5xTOixORrweIxL6oNHmjftl1cpxYjfDADhWA9kInu7U467jxpGuWQARgepiOkOAo6jvRbNro6fWq+3QnUr9rl/jOAUlpSeH/FK8scjmEScIBFYtme8pONKGx3vURGVUM+PPrC8X/CBqV/AZK26kFmHS5p06XO2gfIV5kn1EsQsp1VsnoSzuFgq0qyVTxfY+3SVSeAC77Er+XZz6lHpgmmbYYNjem2bwHJviy40vaM/8mgYzeftcF5lB2NqSH2bSDWX/GJfzPzY9RI8C+XoO0FSYlP2gGiUBib9wo2DAaLruFhwF0Gaxjfm55Vl3cQmhh5lZSJNfAtNv+hmG3TEVylBA6/1m1c2ToX0hc4rJTosi3pUNBo6Jj/3if63qLXeQL0cVkA=
  - secure: Y0Yj6bmrl92uXwCBPem2zk5xMaVGLRr8p58WWT/k1ibqILpnxvQFfSTY1Cx51RvkU+xkmkjcsHJdWYna3WAckwpg6nX9jls62pfuDTlop/A1dbqhVGhIjt9CQE1P1xMFjuqyVHj23HpYxADYgsnCjNf3SXtcY/cjlqQq5rkuUowehdhokYn81NRnrolYe+jyFxkpnt2aUNbYxuHFR5fKM4DZegXyqbQxrZ12cb0nAk9DInU7PJaHEhLZn8jKKNDSjBfn2O0p9VQwayY2Mli1NEb2jDzrXvN0mxtiS+L7oEztNQotcJXKkfWyagMUgAGYc9YJwVh9T+EOgGMi0/tHsNqRo9Fpw9KvmESc1uJypZVJwPBgdfz4lvepngrNy82OrK4wBlcJnVfpnd5URX1qTjuslFnlLr6KlxRtbH0bxrJr7bh4Dvo+KbkQ5eEd1Wblg1bNVj47KcSxns2mRKVEj5C+kowIucbOozff2MK/c8sZjoMv1y8j1/8G9xUkPukAid7U7RkOOeW6+IRPNbT/j0hDLsVIdGTdaQKEZUzD3vCAqofKMQTnlFflBkEJhlpRa5Aqi1MjW8iBml6WPNUx9D6tudjHkhBGOOvIvYOA4sponLoDmSgigdNBPxaMQaHpyjYYvRN35hs+xxMY7707w1aoIaU9Z/he/pSL4BwQhUU=
